### ISSUE TITLE
ValueError: 'noarch' is not a valid Arch

### ISSUE THREAD

**Issue by lukaszachy** [RedHatQE/newa#51]
So I picked one errata to try, it has just one build and it is noarch:

```
$ newa event -e 131301
06/21/2024 04:02:23 PM Using state directory /var/tmp/newa/run-3
Traceback (most recent call last):
  File "/home/lzachar/.local/bin/newa", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/lzachar/.local/share/pipx/venvs/newa/lib64/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzachar/.local/share/pipx/venvs/newa/lib64/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/lzachar/.local/share/pipx/venvs/newa/lib64/python3.12/site-packages/click/core.py", line 1719, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzachar/.local/share/pipx/venvs/newa/lib64/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzachar/.local/share/pipx/venvs/newa/lib64/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzachar/.local/share/pipx/venvs/newa/lib64/python3.12/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzachar/.local/share/pipx/venvs/newa/lib64/python3.12/site-packages/newa/cli.py", line 134, in cmd_event
    errata = ErrataTool(url=et_url).get_errata(event)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzachar/.local/share/pipx/venvs/newa/lib64/python3.12/site-packages/newa/__init__.py", line 488, in get_errata
    archs.update([Arch(a) for a in channel])
                  ^^^^^^^
  File "/usr/lib64/python3.12/enum.py", line 744, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/enum.py", line 1158, in __new__
    raise ve_exc
ValueError: 'noarch' is not a valid Arch

```

**Comment by kkaarreell** [comment]
The first bug reported by a user. Woohoo!
