### ISSUE TITLE
ValueError: 'module' is not a valid ErratumContentType

### ISSUE THREAD

**Issue by lukaszachy** [RedHatQE/newa#59]
Rhel-8 is full of modules. Hit with `newa event -e 135141`.

```
$ newa event -e 135141
07/01/2024 01:56:30 PM Using state directory /var/tmp/newa/run-7
Traceback (most recent call last):
  File "/usr/bin/newa", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1719, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/newa/cli.py", line 134, in cmd_event
    errata = ErrataTool(url=et_url).get_errata(event)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/newa/__init__.py", line 497, in get_errata
    content_type=ErratumContentType(
                 ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/enum.py", line 744, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/enum.py", line 1158, in __new__
    raise ve_exc
ValueError: 'module' is not a valid ErratumContentType
```

**Comment by kkaarreell** [comment]
Right, modular content support is not yet implemented. One thing to decide is how individual streams should be handled. Do we want a standalone Jira epic per module stream (similarly to how it's currently implemented for RPM advisories for multiple releases)? Or rather a common epic with multiple tasks for individual streams.
